### PR TITLE
[FIX] Address several PET bug issues

### PR DESCRIPTION
**Pull request by dlevitas**
Further addresses #92

This PR address several issues pertaining to PET BIDS conversion:

1). Detect `pet/blood` data (both json and corresponding tsv files) and separate metadata requirements from `pet/pet` data.

2). Convert `pet/blood` data into a BIDS-compliant dataset. 
3). Accepts ECAT-formatted data (`.v`, `.v.gz`)
4). Utilizes `parallel` for file renaming (rare, but but otherwise incredibly slow when renaming thousands of files)

### CODE REVIEW

**Comment by dlevitas** [comment]
@bendhouseart would you mind reviewing the functionality introduced in this PR?

**Comment by bendhouseart** [comment]
Checked the following on my end:

setup | success | status msg/error |                            
---------------------------------------------|-------------------------------------|------------------------------------
Phantom with the example spreadsheet |  |  
Phantom with an "incorrect" spreadsheet, then correcting in metadata editor | fail | "status_msg": "failed to run bids -- code:1\n/app/handler/convert.js:5\nimport { readFileSync, writeFileSync, openSync, writeSync, closeSync, lstatSync, unlinkSync, linkSync } from 'fs';\n^^^^^^\n\nSyntaxError: Cannot use import statement outside a module\n    at Object.compileFunction (node:vm:360
Real data from one of our COX-2 Subjects |  |

**Comment by bendhouseart** [comment]
The real data seems to be getting stuck somewhere, it's been running several minutes and this is the state of the output dir:

```65b82e574c1a13a8909364ee % ls
preprocess.err	preprocess.log	sub-09
```

**Comment by dlevitas** [comment]
Are there any errors in the web browser console?

**Comment by bendhouseart** [comment]
Only at the finalize page, see:
Screenshot 2024-01-29 at 7 35 47 PM

**Comment by dlevitas** [comment]
Just pushed come commits that should resolve the finalize page error

**Comment by bendhouseart** [comment]
Take #2 following changes added with commit 8ad5b63

setup | success | status msg/error | ID |                           
---------------------------------------------|-------------------------------------|------------------------------------ | ---------------------------------------------|
Phantom with the example spreadsheet |  |  |  |
Phantom with an "incorrect" spreadsheet, then correcting in metadata editor |  |  |
Real data from one of our COX-2 Subjects |  |  |

Not complete until each row is filled out*

**Comment by bendhouseart** [comment]
Screenshot 2024-01-30 at 2 52 58 PM

**Comment by bendhouseart** [comment]
One thing I did notice that the metadata menu/editor doesn't agree with the value in the spreadsheet. But it's reading in everything else correctly and producing an invalid output (that's what I wanted to see) as a result.

Screenshot 2024-01-30 at 3 01 10 PM
Screenshot 2024-01-30 at 3 00 12 PM

**Comment by dlevitas** [comment]
> One thing I did notice that the metadata menu/editor doesn't agree with the value in the spreadsheet. But it's reading in everything else correctly and producing an invalid output (that's what I wanted to see) as a result.

This is by design for that specific PET metadata value. If that value is `True` and the corresponding tsv header column doesn't exist, ezBIDS changes the value to `False`. It's just a way to alert users to their potential mistakes.

**Comment by bendhouseart** [comment]
Got it, so I just tried to rerun the data that produced the above screenshots, but that when I do ezBIDS doesn't pick up on the petness of the files and run dcm2niix instead.

Screenshot 2024-01-30 at 2 52 58 PM

Which is weird.

**Comment by dlevitas** [comment]
ezBIDS 

> Got it, so I just tried to rerun the data that produced the above screenshots, but that when I do ezBIDS doesn't pick up on the petness of the files and run dcm2niix instead.

Did your second upload contain an `ezBIDS_template.json` file? If so, I may need to add a check to have that ignored for PET data.

**Comment by bendhouseart** [comment]
Also, I think the issue with it not picking up the pet files was because I had excel open, I would call this good to go for now and merge it.

**Comment by dlevitas** [comment]
I'm going to perform a few additional tests, but I'll plan on merging this PR at the end of the week.

**Comment by dlevitas** [comment]
@bendhouseart when you get the chance, would you mind looking over commit 64043f3?

I ended up adding ECAT support (via `ecatpet2bids`) and merged the functionality of `find_dicomdir.py` and `find_petdir.py` into the former and removed the latter. To test this, I uploaded a "dataset" containing 5 different types of data:
* MRI dicoms
* MRI NIfTI/JSON files
* PET dicoms
* PET ECAT-formatted files (.v)
* PET NIFTI/JSON (and blood recording) files, transformed previously with pypet2bids. 

All files were successfully identified and transformed based on their datatype and format (i.e. MRI dicoms --> `dcm2niix`; PET dicoms --> `dcm2niix4pet`; PET ECAT --> `ecatpet2bids`).

The PET data I was able to find online is still rather small, so I haven't replicated your inflation error from before.

**Comment by bendhouseart** [comment]
Just tested the final (it's absolutely final i'm sure) iteration you pushed yesterday and it works flawlessly with our real data.

Screenshot 2024-02-06 at 11 07 55 AM

**Comment by dlevitas** [comment]
@bendhouseart I recall us discussing how ezBIDS should handle PET metadata spreadsheet(s), landing on users needing to place a spreadsheet in each corresponding raw data folder. 

This approach is fine by me; however, I'm also amenable to a provenance framework (akin to BIDS) where all raw data folders or files underneath a spreadsheet are assumed to have that specified metadata. As an example:

```
-- pet_metadata_spreadsheet.xlsx
-- sub1_raw_data
---- run1_ecat.v
---- run2_ecat.v
````

So in this example, both ECAT-formatted raw PET data would be given the metadata in the folder above. If this isn't how PET metadata would be stored, or if it's outside the scope of the PR, we can ignore this.

**Comment by bendhouseart** [comment]
Out of scope!

What's going to me more helpful to the user, in the immediate, is them being clued in on how to format and place their PET spreadsheets. But, really I don't want to make any assumptions or optimizations until the current iteration gets tested on real users.

**Pull request merged**
