### PR TITLE
1 enable user to initialize dwi pipeline from ezbids

### PR DESCRIPTION
**Pull request by nicoalee**
Added option to either send to brainlife, or send to brainlife and trigger DWI pipeline

Screenshot 2023-08-30 at 12 01 41

### CODE REVIEW

**Comment by nicoalee** [comment]
- [ ] Confirm that corresponding changes in warehouse are complete and can support this

**Comment by dlevitas** [comment]
@nicoalee are you inquiring whether we have a test instance of brainlife (and ezBIDS)?

**Comment by nicoalee** [comment]
> @nicoalee are you inquiring whether we have a test instance of brainlife (and ezBIDS)?

Yes, originally I was hoping that we had a test instance and I could deploy my changes onto it. For now, I'm going to check this box as having it working on a local dev instance should be sufficient.

**Comment by dlevitas** [comment]
Sounds good, we did once have test instances of both ezBIDS and brainlife.io, but I believe they're no longer functional (the ezBIDS test instance at least).

**Comment by dlevitas** [comment]
This looks good to me, I will go ahead and merge.

**Pull request merged**
